# # # build environment
# # FROM node:13.12.0-alpine as build
# # WORKDIR /app
# # ENV PATH /app/node_modules/.bin:$PATH
# # COPY package.json ./
# # COPY package-lock.json ./
# # RUN npm install --legacy-peer-deps
# # COPY . ./
# # RUN npm run build
# # # production environment
# # FROM nginx:stable-alpine
# # COPY —from=build /app/build /usr/share/nginx/html
# # EXPOSE 3000
# # CMD [“nginx”, “-g”, “daemon off;”]
# # Stage 1: Build environment
# FROM node:14.17.0-alpine AS build
# WORKDIR /main
# ENV PATH /main/node_modules/.bin:$PATH

# # Install dependencies
# COPY package.json .
# COPY package-lock.json .
# RUN npm install --legacy-peer-deps
# COPY . .

# # Build the application
# RUN npm run build

# # Stage 2: Production environment
# FROM nginx:stable-alpine
# COPY --from=build /main/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
